sudo: true

language: ruby

services:
  - docker
before_script:
  - cp config/database.sample.yml config/database.yml
  - docker-compose -f docker-compose.test.yml build
  - docker-compose -f docker-compose.test.yml run --user='root' --entrypoint chown server_app_test -R app:app .
  - docker-compose -f docker-compose.test.yml run server_app_test bundle exec rake db:create
  - docker-compose -f docker-compose.test.yml run server_app_test bundle exec rake db:schema:load
  - docker-compose -f docker-compose.test.yml run server_app_test bundle exec rails webpacker:binstubs
script:
  - docker-compose -f docker-compose.test.yml run server_app_test yarn run es-lint
  - docker-compose -f docker-compose.test.yml run server_app_test bundle exec rubocop .
  - docker-compose -f docker-compose.test.yml run server_app_test bundle exec rspec
